#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidExamples.Resource", IsApplication=true)]

namespace AndroidExamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int font = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int fontProviderAuthority = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fontProviderPackage = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int fontProviderQuery = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int fontStyle = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int fontVariationSettings = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int fontWeight = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int ttcIndex = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int notification_action_color_filter = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int notification_icon_bg_color = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ripple_material_light = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int secondary_text_default_material_light = 2130837507;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int compat_button_inset_horizontal_material = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int compat_button_inset_vertical_material = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int compat_button_padding_horizontal_material = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int compat_button_padding_vertical_material = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int compat_control_corner_material = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int compat_notification_large_icon_max_height = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int compat_notification_large_icon_max_width = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int notification_action_icon_size = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int notification_action_text_size = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int notification_big_circle_margin = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int notification_content_margin_start = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_large_icon_height = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_large_icon_width = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_main_column_padding_top = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int notification_media_narrow_margin = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int notification_right_icon_size = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int notification_right_side_padding_top = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int notification_small_icon_background_padding = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int notification_small_icon_size_as_large = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int notification_subtext_size = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int notification_top_pad = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int notification_top_pad_large_text = 2130903061;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int notification_action_background = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int notification_bg = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int notification_bg_low = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int notification_bg_low_normal = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_bg_low_pressed = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_bg_normal = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_bg_normal_pressed = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_icon_background = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_template_icon_bg = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_template_icon_low_bg = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_tile_bg = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notify_panel_notification_icon_bg = 2130968588;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F050000
			public const int AboutUsCloseButton = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int AboutUsEmailSupportTextView = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int AboutUsModuleInfoTextView = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int AboutUsVersionTextView = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int AboutUsWebsiteTextView = 2131034116;
			
			// aapt resource value: 0x7F050016
			public const int actions = 2131034134;
			
			// aapt resource value: 0x7F050012
			public const int action_container = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int action_divider = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int action_image = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int action_text = 2131034133;
			
			// aapt resource value: 0x7F050017
			public const int async = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int blocking = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int button_message_image_layout_button = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int button_message_image_layout_image = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int button_message_image_layout_message = 2131034139;
			
			// aapt resource value: 0x7F050005
			public const int CameraPreiewRelativeLayout = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int CameraPreviewCaptureImageButton = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int CameraPreviewSwitchCameraImageButton = 2131034119;
			
			// aapt resource value: 0x7F05001C
			public const int cannyImageButton = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int capturedImageButton = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int chronometer = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int colorMapImageButton = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int distorImageButton = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int forever = 2131034145;
			
			// aapt resource value: 0x7F050008
			public const int GotoCamera2Button = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int GotoFaceDetectionButton = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int GotoFeatureMatchingButton = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int GotoLicensePlateRecognitionButton = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int GotoPedestrianDetectionButton = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int GotoPlanarSubdivisionButton = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int GotoTrafficSignRecognitionButton = 2131034126;
			
			// aapt resource value: 0x7F050022
			public const int icon = 2131034146;
			
			// aapt resource value: 0x7F050023
			public const int icon_group = 2131034147;
			
			// aapt resource value: 0x7F050024
			public const int info = 2131034148;
			
			// aapt resource value: 0x7F050025
			public const int italic = 2131034149;
			
			// aapt resource value: 0x7F050026
			public const int line1 = 2131034150;
			
			// aapt resource value: 0x7F050027
			public const int line3 = 2131034151;
			
			// aapt resource value: 0x7F05000F
			public const int MyImage = 2131034127;
			
			// aapt resource value: 0x7F050028
			public const int normal = 2131034152;
			
			// aapt resource value: 0x7F050029
			public const int notification_background = 2131034153;
			
			// aapt resource value: 0x7F05002A
			public const int notification_main_column = 2131034154;
			
			// aapt resource value: 0x7F05002B
			public const int notification_main_column_container = 2131034155;
			
			// aapt resource value: 0x7F05002D
			public const int opencl_preference_radio_group = 2131034157;
			
			// aapt resource value: 0x7F05002C
			public const int openCVLicenseTextView = 2131034156;
			
			// aapt resource value: 0x7F050010
			public const int PlanarSubdivisionImageView = 2131034128;
			
			// aapt resource value: 0x7F05002E
			public const int previewImageButton = 2131034158;
			
			// aapt resource value: 0x7F050011
			public const int RedrawSubdivisionButton = 2131034129;
			
			// aapt resource value: 0x7F05002F
			public const int relativeLayout1 = 2131034159;
			
			// aapt resource value: 0x7F050030
			public const int relativeLayout2 = 2131034160;
			
			// aapt resource value: 0x7F050031
			public const int relativeLayout3 = 2131034161;
			
			// aapt resource value: 0x7F050032
			public const int right_icon = 2131034162;
			
			// aapt resource value: 0x7F050033
			public const int right_side = 2131034163;
			
			// aapt resource value: 0x7F050034
			public const int tag_transition_group = 2131034164;
			
			// aapt resource value: 0x7F050035
			public const int tag_unhandled_key_event_manager = 2131034165;
			
			// aapt resource value: 0x7F050036
			public const int tag_unhandled_key_listeners = 2131034166;
			
			// aapt resource value: 0x7F050037
			public const int text = 2131034167;
			
			// aapt resource value: 0x7F050038
			public const int text2 = 2131034168;
			
			// aapt resource value: 0x7F050039
			public const int textView1 = 2131034169;
			
			// aapt resource value: 0x7F05003A
			public const int time = 2131034170;
			
			// aapt resource value: 0x7F05003B
			public const int title = 2131034171;
			
			// aapt resource value: 0x7F05003C
			public const int toolbarLayout = 2131034172;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F060000
			public const int status_bar_notification_info_maxnum = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F070000
			public const int about_us = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int AndroidExamples = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int button_message_image_layout = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int CameraPreviewLayout = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int LicenseDisplay = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int notification_action = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int notification_action_tombstone = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int notification_template_custom_big = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int notification_template_icon_group = 2131165192;
			
			// aapt resource value: 0x7F070009
			public const int notification_template_part_chronometer = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int notification_template_part_time = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int opencl_preference = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int PlanarSubdivision = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int Setting = 2131165197;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F080000
			public const int LICENSE = 2131230720;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090009
			public const int application_name = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int application_version = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int application_website = 2131296267;
			
			// aapt resource value: 0x7F090000
			public const int Camera = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int Camera2 = 2131296257;
			
			// aapt resource value: 0x7F09000C
			public const int email_support = 2131296268;
			
			// aapt resource value: 0x7F090002
			public const int FaceDetection = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int FeatureMatching = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int HelloWorld = 2131296260;
			
			// aapt resource value: 0x7F09000D
			public const int menu_option_about_us = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int menu_option_settings = 2131296270;
			
			// aapt resource value: 0x7F090005
			public const int PedestrianDetection = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int PlanarSubdivision = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int RedrawSubdivision = 2131296263;
			
			// aapt resource value: 0x7F09000F
			public const int show_software_license = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int software_license = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int status_bar_notification_info_overflow = 2131296273;
			
			// aapt resource value: 0x7F090008
			public const int TrafficSignRecognition = 2131296264;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Line2 = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Time = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Title = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int Widget_Compat_NotificationActionContainer = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int Widget_Compat_NotificationActionText = 2131361798;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F010000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007 }
			public static int[] FontFamily = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F010001,0x7F010008,0x7F010009,0x7F01000A,0x7F01000B }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771969,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0C0000
			public const int file_paths = 2131492864;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
