//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidExamples
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int GotoCameraButton = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int GotoFaceDetectionButton = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int GotoLicensePlateRecognitionButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int GotoPedestrianDetectionButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int GotoPlanarSubdivisionButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int GotoSURFFeaturesButton = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int GotoTrafficSignRecognitionButton = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int MyImage = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int PlanarSubdivisionImageView = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int RedrawSubdivisionButton = 2131034119;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AndroidExamples = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PlanarSubdivision = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int ApplicationName = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Camera = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int FaceDetection = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int HelloWorld = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int PedestrianDetection = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int PlanarSubdivision = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int RedrawSubdivision = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int SURFFeatures = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int TrafficSignRecognition = 2130968582;
			
			private String()
			{
			}
		}
	}
}
