#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidExamples.Resource", IsApplication=true)]

namespace AndroidExamples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int CameraPreiewRelativeLayout = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int CameraPreviewCaptureImageButton = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int CameraPreviewSwitchCameraImageButton = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int GotoCameraButton = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int GotoFaceDetectionButton = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int GotoLicensePlateRecognitionButton = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int GotoPedestrianDetectionButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int GotoPlanarSubdivisionButton = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int GotoSURFFeaturesButton = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int GotoTrafficSignRecognitionButton = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int MyImage = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int PlanarSubdivisionImageView = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int RedrawSubdivisionButton = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int cannyImageButton = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int capturedImageButton = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int colorMapImageButton = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int distorImageButton = 2131034129;
			
			// aapt resource value: 0x7f05000e
			public const int previewImageButton = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int relativeLayout1 = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int relativeLayout2 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int relativeLayout3 = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int toolbarLayout = 2131034120;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AndroidExamples = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CameraPreviewLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlanarSubdivision = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int ApplicationName = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Camera = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int FaceDetection = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int HelloWorld = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int PedestrianDetection = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int PlanarSubdivision = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int RedrawSubdivision = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int SURFFeatures = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int TrafficSignRecognition = 2130968582;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
