//This file is automatically generated by CMAKE. DO NOT MODIFY.
using System;
using System.Collections.Generic;

namespace Emgu.CV
{
   public partial class CvInvoke
   {
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string EXTERN_LIBRARY = "cvextern";
	  
	  /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string EXTERN_GPU_LIBRARY = EXTERN_LIBRARY;

      /// <summary>
      /// The file name of the opencv_ffmpeg library
      /// </summary>
      public const string OPENCV_FFMPEG_LIBRARY = "";

	   
      /// <summary>
      /// The file name of the core library
      /// </summary>
      public const string OPENCV_CORE_LIBRARY = "opencv_core"; 
      /// <summary>
      /// The file name of the imgproc library
      /// </summary>
      public const string OPENCV_IMGPROC_LIBRARY = "opencv_imgproc"; 
      /// <summary>
      /// The file name of the video library
      /// </summary>
      public const string OPENCV_VIDEO_LIBRARY = "opencv_video"; 
      /// <summary>
      /// The file name of the flann library
      /// </summary>
      public const string OPENCV_FLANN_LIBRARY = "opencv_flann"; 
      /// <summary>
      /// The file name of the ml library
      /// </summary>
      public const string OPENCV_ML_LIBRARY = "opencv_ml"; 
      /// <summary>
      /// The file name of the highgui library
      /// </summary>
      public const string OPENCV_HIGHGUI_LIBRARY = "opencv_highgui"; 
      /// <summary>
      /// The file name of the objdetect library
      /// </summary>
      public const string OPENCV_OBJDETECT_LIBRARY = "opencv_objdetect"; 
      /// <summary>
      /// The file name of the features2d library
      /// </summary>
      public const string OPENCV_FEATURES2D_LIBRARY = "opencv_features2d"; 
      /// <summary>
      /// The file name of the calib3d library
      /// </summary>
      public const string OPENCV_CALIB3D_LIBRARY = "opencv_calib3d"; 
      /// <summary>
      /// The file name of the legacy library
      /// </summary>
      public const string OPENCV_LEGACY_LIBRARY = "opencv_legacy"; 
      /// <summary>
      /// The file name of the contrib library
      /// </summary>
      public const string OPENCV_CONTRIB_LIBRARY = "opencv_contrib"; 
      /// <summary>
      /// The file name of the gpulegacy library
      /// </summary>
      public const string OPENCV_GPULEGACY_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpuarithm library
      /// </summary>
      public const string OPENCV_GPUARITHM_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpuwarping library
      /// </summary>
      public const string OPENCV_GPUWARPING_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpu library
      /// </summary>
      public const string OPENCV_GPU_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpufilters library
      /// </summary>
      public const string OPENCV_GPUFILTERS_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpuimgproc library
      /// </summary>
      public const string OPENCV_GPUIMGPROC_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpuoptflow library
      /// </summary>
      public const string OPENCV_GPUOPTFLOW_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpustereo library
      /// </summary>
      public const string OPENCV_GPUSTEREO_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpubgsegm library
      /// </summary>
      public const string OPENCV_GPUBGSEGM_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpufeatures2d library
      /// </summary>
      public const string OPENCV_GPUFEATURES2D_LIBRARY = ""; 
      /// <summary>
      /// The file name of the ocl library
      /// </summary>
      public const string OPENCV_OCL_LIBRARY = ""; 
      /// <summary>
      /// The file name of the photo library
      /// </summary>
      public const string OPENCV_PHOTO_LIBRARY = "opencv_photo"; 
      /// <summary>
      /// The file name of the bioinspired library
      /// </summary>
      public const string OPENCV_BIOINSPIRED_LIBRARY = "opencv_bioinspired"; 
      /// <summary>
      /// The file name of the superres library
      /// </summary>
      public const string OPENCV_SUPERRES_LIBRARY = ""; 
      /// <summary>
      /// The file name of the nonfree library
      /// </summary>
      public const string OPENCV_NONFREE_LIBRARY = "opencv_nonfree"; 
      /// <summary>
      /// The file name of the stitching library
      /// </summary>
      public const string OPENCV_STITCHING_LIBRARY = "opencv_stitching"; 
      /// <summary>
      /// The file name of the videostab library
      /// </summary>
      public const string OPENCV_VIDEOSTAB_LIBRARY = "opencv_videostab"; 
      /// <summary>
      /// The file name of the optim library
      /// </summary>
      public const string OPENCV_OPTIM_LIBRARY = "opencv_optim"; 
      /// <summary>
      /// The file name of the softcascade library
      /// </summary>
      public const string OPENCV_SOFTCASCADE_LIBRARY = "opencv_softcascade"; 
      /// <summary>
      /// The file name of the cudev library
      /// </summary>
      public const string OPENCV_CUDEV_LIBRARY = ""; 
      /// <summary>
      /// The file name of the gpucodec library
      /// </summary>
      public const string OPENCV_GPUCODEC_LIBRARY = "";
	  
      /// <summary>
      /// The List of the opencv modules
      /// </summary>
	  public static List<String> OpenCVModuleList = new List<String>
	  {
         OPENCV_FFMPEG_LIBRARY,
	     OPENCV_CORE_LIBRARY,
	     OPENCV_IMGPROC_LIBRARY,
	     OPENCV_VIDEO_LIBRARY,
	     OPENCV_FLANN_LIBRARY,
	     OPENCV_ML_LIBRARY,
	     OPENCV_HIGHGUI_LIBRARY,
	     OPENCV_OBJDETECT_LIBRARY,
	     OPENCV_FEATURES2D_LIBRARY,
	     OPENCV_CALIB3D_LIBRARY,
	     OPENCV_LEGACY_LIBRARY,
	     OPENCV_CONTRIB_LIBRARY,
	     OPENCV_PHOTO_LIBRARY,
	     OPENCV_BIOINSPIRED_LIBRARY,
	     OPENCV_NONFREE_LIBRARY,
	     OPENCV_STITCHING_LIBRARY,
	     OPENCV_VIDEOSTAB_LIBRARY,
	     OPENCV_OPTIM_LIBRARY,
	     OPENCV_SOFTCASCADE_LIBRARY,
         EXTERN_LIBRARY
      };

	  
   }
}
