//----------------------------------------------------------------------------
//  Copyright (C) 2004-2026 by EMGU Corporation. All rights reserved.
//----------------------------------------------------------------------------
using System;
using Emgu.CV;
using Emgu.CV.Alphamat;
using Emgu.CV.CvEnum;
using Emgu.CV.Structure;
using Emgu.CV.Util;

#if VS_TEST
using Microsoft.VisualStudio.TestTools.UnitTesting;
using TestAttribute = Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute;
using TestFixture = Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute;
#elif NETFX_CORE
using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
using TestAttribute = Microsoft.VisualStudio.TestPlatform.UnitTestFramework.TestMethodAttribute;
using TestFixture = Microsoft.VisualStudio.TestPlatform.UnitTestFramework.TestClassAttribute;
#else
using NUnit.Framework;
#endif

namespace Emgu.CV.Test
{
    [TestFixture]
    public class AutoTestAlphamat
    {
        [Test]
        public void TestInfoFlow()
        {
            using (Mat image = EmguAssert.LoadMat("alphamat_plant.jpg"))
            using (Mat trimap = EmguAssert.LoadMat("alphamat_plant_trimap.png", ImreadModes.Grayscale))
            using (Mat expected = EmguAssert.LoadMat("alphamat_plant_result.png", ImreadModes.Grayscale))
            using (Mat result = new Mat())
            {
                EmguAssert.IsFalse(image.IsEmpty);
                EmguAssert.IsFalse(trimap.IsEmpty);
                EmguAssert.IsFalse(expected.IsEmpty);

                AlphamatInvoke.InfoFlow(image, trimap, result);

                EmguAssert.IsFalse(result.IsEmpty);
                EmguAssert.AreEqual(image.Size, result.Size);
                EmguAssert.AreEqual(1, result.NumberOfChannels);
                EmguAssert.AreEqual(expected.Size, result.Size);

                using (Mat diff = new Mat())
                {
                    CvInvoke.AbsDiff(expected, result, diff);
                    MCvScalar meanDiff = CvInvoke.Mean(diff);
                    // The reference output was generated by the same algorithm; a small
                    // mean difference is expected from floating point/BLAS differences
                    // across platforms and OpenCV versions, but a large one indicates a
                    // real regression.
                    EmguAssert.IsTrue(
                        meanDiff.V0 < 5.0,
                        String.Format("Mean absolute difference from reference matte was {0}, expected < 5.0", meanDiff.V0));
                }
            }
        }

        [Test]
        public void TestInfoFlowMismatchedSizeThrows()
        {
            using (Mat image = EmguAssert.LoadMat("alphamat_plant.jpg"))
            using (Mat badTrimap = new Mat(10, 10, DepthType.Cv8U, 1))
            using (Mat result = new Mat())
            {
                badTrimap.SetTo(new MCvScalar(128));

                CvException ex = Assert.Throws<CvException>(() =>
                {
                    AlphamatInvoke.InfoFlow(image, badTrimap, result);
                });
                EmguAssert.IsTrue(ex.ErrorMessage.Contains("size"));
            }
        }
    }
}
