#!/bin/sh

cd ../../..

cd vtk
CFLAGS=-fPIC CXXFLAGS=-fPIC cmake -DBUILD_TESTING:BOOL=FALSE -DBUILD_SHARED_LIBS:BOOL=FALSE -DCMAKE_BUILD_TYPE:STRING="RELEASE" .
make
cd ..

cd platforms/ubuntu/16.04
mkdir -p build
cd build
cmake -DBUILD_TESTS:BOOL=FALSE -DBUILD_PERF_TESTS:BOOL=FALSE -DBUILD_opencv_apps:BOOL=FALSE -DBUILD_opencv_python2:BOOL=FALSE -DBUILD_DOCS:BOOL=FALSE -DWITH_TBB:BOOL=TRUE -DWITH_CUDA:BOOL=FALSE -DWITH_OPENCL:BOOL=FALSE -DWITH_IPP:BOOL=FALSE -DWITH_EIGEN:BOOL=FALSE  -DOPENCV_EXTRA_MODULES_PATH=../../../../opencv_contrib/modules -DBUILD_opencv_ts:BOOL=FALSE -DBUILD_SHARED_LIBS:BOOL=FALSE -DVTK_DIR:String="$PWD/vtk" -DCMAKE_BUILD_TYPE:String="Release" ../../../..
make
cd ..
