#!/bin/sh
cd "$(dirname "$0")"

cd Assets
cd Emgu.CV

mkdir -p Assets
cd Assets
mkdir -p Scripts
cd Scripts
rm -rf Emgu.Util
mkdir -p Emgu.Util
rm -rf Emgu.CV
mkdir -p Emgu.CV
cd Emgu.CV
mkdir -p PInvoke
cd ..
rm -rf Emgu.CV.Contrib
mkdir -p Emgu.CV.Contrib
rm -rf Emgu.CV.OCR
mkdir -p Emgu.CV.OCR
rm -rf Emgu.CV.Models
mkdir -p Emgu.CV.Models
cd ..
cd ..
cd ..
cd ..

cp ../opencv/LICENSE Assets/Emgu.CV/Documentation/opencv.license.txt
cp ../Emgu.CV.Extern/tesseract/libtesseract/tesseract-ocr.git/LICENSE Assets/Emgu.CV/Documentation/tesseract.ocr.license.txt


cp ../Emgu.Util/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.Util/

cp ../Emgu.CV/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Calib3d Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Color Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Core Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Gapi Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Cvb Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Dnn Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Features2D Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Flann Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Geodetic Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Imgproc Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Ml Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Objdetect Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Ocl Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Optflow Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Photo Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke
cp -r ../Emgu.CV/PInvoke Assets/Emgu.CV/Assets/Scripts/Emgu.CV/ 

rm -rf Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/iOS
rm -rf Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/Android
rm -rf Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/Windows.Store
cp -r ../Emgu.CV/PointAndLine Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Reflection Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Shape Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Stitching Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Superres Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
# cp -r ../Emgu.CV/Tiff Assets/Emgu.CV/Emgu.CV/
cp -r ../Emgu.CV/Util Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Video Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Videoio Assets/Emgu.CV/Assets/Scripts/Emgu.CV/
cp -r ../Emgu.CV/Videostab Assets/Emgu.CV/Assets/Scripts/Emgu.CV/

mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Alphamat
cp -r ../Emgu.CV.Contrib/Alphamat/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Alphamat
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Aruco
cp -r ../Emgu.CV.Contrib/Aruco/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Aruco
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/BgSegm
cp -r ../Emgu.CV.Contrib/BgSegm/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/BgSegm
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Bioinspired
cp -r ../Emgu.CV.Contrib/Bioinspired/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Bioinspired
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/DnnModern
cp -r ../Emgu.CV.Contrib/DnnModern/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/DnnModern
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Dpm
cp -r ../Emgu.CV.Contrib/Dpm/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Dpm
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Face
cp -r ../Emgu.CV.Contrib/Face/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Face
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Freetype
cp -r ../Emgu.CV.Contrib/Freetype/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Freetype
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Fuzzy
cp -r ../Emgu.CV.Contrib/Fuzzy/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Fuzzy
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Hfs
cp -r ../Emgu.CV.Contrib/Hfs/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Hfs
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/ImgHash
cp -r ../Emgu.CV.Contrib/ImgHash/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/ImgHash
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/LineDescriptor
cp -r ../Emgu.CV.Contrib/LineDescriptor/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/LineDescriptor
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/PhaseUnwrapping
cp -r ../Emgu.CV.Contrib/PhaseUnwrapping/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/PhaseUnwrapping
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Plot
cp -r ../Emgu.CV.Contrib/Plot/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Plot
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Saliency
cp -r ../Emgu.CV.Contrib/Saliency/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Saliency
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Text
cp -r ../Emgu.CV.Contrib/Text/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Text
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Tracking
cp -r ../Emgu.CV.Contrib/Tracking/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Tracking 
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XFeatures2D
cp -r ../Emgu.CV.Contrib/XFeatures2D/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XFeatures2D
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XImgproc
cp -r ../Emgu.CV.Contrib/XImgproc/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XImgproc
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XObjdetect
cp -r ../Emgu.CV.Contrib/XObjdetect/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XObjdetect
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XPhoto
cp -r ../Emgu.CV.Contrib/XPhoto/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XPhoto
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Quality
cp -r ../Emgu.CV.Contrib/Quality/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Quality
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Stereo
cp -r ../Emgu.CV.Contrib/Stereo/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Stereo
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/SurfaceMatching
cp -r ../Emgu.CV.Contrib/SurfaceMatching/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/SurfaceMatching
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/DnnSuperres
cp -r ../Emgu.CV.Contrib/DnnSuperres/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/DnnSuperres
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/IntensityTransform
cp -r ../Emgu.CV.Contrib/IntensityTransform/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/IntensityTransform
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Rapid
cp -r ../Emgu.CV.Contrib/Rapid/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Rapid
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Mcc
cp -r ../Emgu.CV.Contrib/Mcc/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Mcc
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Hdf
cp -r ../Emgu.CV.Contrib/Hdf/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Hdf
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/WechatQrcode
cp -r ../Emgu.CV.Contrib/WechatQrcode/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/WechatQrcode

cp -r ../Emgu.CV.OCR/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.OCR/

cp -r ../Emgu.CV.Models/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/
mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/Dnn
cp -r ../Emgu.CV.Models/Dnn/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/Dnn
#mkdir -p Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/DepthAI
#cp -r ../Emgu.CV.Models/DepthAI/*.cs Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/DepthAI


cd Assets/Emgu.CV/Plugins/iOS
if test -f "../../../../../libs/iOS/libcvextern_iphoneos.a"
then
  cp -f ../../../../../Emgu.CV/PInvoke/iOS/libcvextern_iphoneos.a ./
fi
if test -f "../../../../../libs/iOS/libcvextern_simulator.a"
then
  cp -f ../../../../../Emgu.CV/PInvoke/iOS/libcvextern_simulator.a ./
fi
cd ..
if test -d "../../../../platforms/macos/emgucv.bundle"
then
  cp -rf ../../../../platforms/macos/emgucv.bundle ./
fi
cd ..
cd ..
