#!/bin/sh
cd "$(dirname "$0")"

cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.Util/*.cs ../Emgu.Util/

cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/*.cs ../Emgu.CV/
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Calib3d/*.cs ../Emgu.CV/Calib3d
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Color/*.cs ../Emgu.CV/Color 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Core/*.cs ../Emgu.CV/Core 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Gapi/*.cs ../Emgu.CV/Gapi 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Cvb/*.cs ../Emgu.CV/Cvb 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Dnn/*.cs ../Emgu.CV/Dnn  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Features2D/*.cs ../Emgu.CV/Features2D 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Flann/*.cs ../Emgu.CV/Flann 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Geodetic/*.cs ../Emgu.CV/Geodetic 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Imgproc/*.cs ../Emgu.CV/Imgproc 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Ml/*.cs ../Emgu.CV/Ml
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Objdetect/*.cs ../Emgu.CV/Objdetect  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Ocl/*.cs ../Emgu.CV/Ocl 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Optflow/*.cs ../Emgu.CV/Optflow 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Photo/*.cs ../Emgu.CV/Photo
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/*.cs ../Emgu.CV/PInvoke  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/CvType/*.cs ../Emgu.CV/PInvoke/CvType
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/System.Drawing/*.cs ../Emgu.CV/PInvoke/System.Drawing
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PInvoke/Unity/*.cs ../Emgu.CV/PInvoke/Unity
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/PointAndLine/*.cs ../Emgu.CV/PointAndLine 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Reflection/*.cs ../Emgu.CV/Reflection 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Shape/*.cs ../Emgu.CV/Shape
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Stitching/*.cs ../Emgu.CV/Stitching
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Superres/*.cs ../Emgu.CV/Superres
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Util/*.cs ../Emgu.CV/Util 
#cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Tiff/*.cs ../Emgu.CV/Tiff 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Video/*.cs ../Emgu.CV/Video
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Videoio/*.cs ../Emgu.CV/Videoio
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Videostab/*.cs ../Emgu.CV/Videostab
#cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV/Viz/*.cs ../Emgu.CV/Viz 


cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Alphamat/*.cs ../Emgu.CV.Contrib/Alphamat 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Aruco/*.cs ../Emgu.CV.Contrib/Aruco  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/BgSegm/*.cs ../Emgu.CV.Contrib/BgSegm  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Bioinspired/*.cs ../Emgu.CV.Contrib/Bioinspired
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/DnnModern/*.cs ../Emgu.CV.Contrib/DnnModern  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/DnnSuperres/*.cs ../Emgu.CV.Contrib/DnnSuperres
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Dpm/*.cs ../Emgu.CV.Contrib/Dpm  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Face/*.cs ../Emgu.CV.Contrib/Face 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Freetype/*.cs ../Emgu.CV.Contrib/Freetype 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Fuzzy/*.cs ../Emgu.CV.Contrib/Fuzzy
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Hdf/*.cs ../Emgu.CV.Contrib/Hdf
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Hfs/*.cs ../Emgu.CV.Contrib/Hfs
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/ImgHash/*.cs ../Emgu.CV.Contrib/ImgHash
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/IntensityTransform/*.cs ../Emgu.CV.Contrib/IntensityTransform
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/LineDescriptor/*.cs ../Emgu.CV.Contrib/LineDescriptor
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Mcc/*.cs ../Emgu.CV.Contrib/Mcc
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/PhaseUnwrapping/*.cs ../Emgu.CV.Contrib/PhaseUnwrapping/      
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Plot/*.cs ../Emgu.CV.Contrib/Plot  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Quality/*.cs ../Emgu.CV.Contrib/Quality  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Rapid/*.cs ../Emgu.CV.Contrib/Rapid
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Saliency/*.cs ../Emgu.CV.Contrib/Saliency  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Stereo/*.cs ../Emgu.CV.Contrib/Stereo  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/SurfaceMatching/*.cs ../Emgu.CV.Contrib/SurfaceMatching 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Text/*.cs ../Emgu.CV.Contrib/Text 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/Tracking/*.cs ../Emgu.CV.Contrib/Tracking  
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XFeatures2D/*.cs ../Emgu.CV.Contrib/XFeatures2D 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XImgproc/*.cs ../Emgu.CV.Contrib/XImgproc 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XObjdetect/*.cs ../Emgu.CV.Contrib/XObjdetect 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/XPhoto/*.cs ../Emgu.CV.Contrib/XPhoto 
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Contrib/WechatQrcode/*.cs ../Emgu.CV.Contrib/WechatQrcode 

cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/*.cs ../Emgu.CV.Models
cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.Models/Dnn/*.cs ../Emgu.CV.Models/Dnn

cp -r Assets/Emgu.CV/Assets/Scripts/Emgu.CV.OCR/*.cs ../Emgu.CV.OCR 

