//This file is automatically generated by CMAKE. DO NOT MODIFY.
using System;
using System.Collections.Generic;

namespace Emgu.CV
{
   public partial class CvInvoke
   {
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
#if (__IOS__ || UNITY_IPHONE || UNITY_WEBGL) && (!UNITY_EDITOR)
      public const string ExternLibrary = "__Internal";
#else
      public const string ExternLibrary = "cvextern";
#endif
	  
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string ExternCudaLibrary = ExternLibrary;

      /// <summary>
      /// The file name of the opencv_ffmpeg library
      /// </summary>
      public const string OpencvFFMpegLibrary = "opencv_videoio_ffmpeg4130";

      
	  
      /// <summary>
      /// The List of the opencv modules
      /// </summary>
	  public static List<String> OpenCVModuleList = new List<String>
	  {
#if !(__ANDROID__ || __IOS__ || UNITY_IPHONE  || UNITY_WEBGL || UNITY_ANDROID || NETFX_CORE)
        OpencvFFMpegLibrary,
#endif        
        
        ExternLibrary
      };

	  
   }
}
